# Generated by Django 4.1.7 on 2023-05-12 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='recursos_humanos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_admissao',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 17, 17, 17, 760344, tzinfo=datetime.timezone.utc), verbose_name='Data de admissão'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_senha',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 17, 17, 17, 760344, tzinfo=datetime.timezone.utc), verbose_name='Data da ultima troca de senha'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_criacao',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 17, 17, 17, 764324, tzinfo=datetime.timezone.utc), verbose_name='Data de criação'),
        ),
    ]
