# Generated by Django 4.1.7 on 2023-04-07 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_alter_setor_options_alter_customuser_data_admissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_admissao',
            field=models.DateField(default=datetime.datetime(2023, 4, 7, 17, 52, 49, 226600, tzinfo=datetime.timezone.utc), verbose_name='Data de admissão'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_senha',
            field=models.DateField(default=datetime.datetime(2023, 4, 7, 17, 52, 49, 226600, tzinfo=datetime.timezone.utc), verbose_name='Data da ultima troca de senha'),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gestor',
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_criacao',
            field=models.DateField(default=datetime.datetime(2023, 4, 7, 17, 52, 49, 229600, tzinfo=datetime.timezone.utc), verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gestor',
            field=models.BooleanField(default=False, verbose_name='Gestor'),
        ),
    ]
