# Generated by Django 4.1.7 on 2023-03-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_alter_customuser_data_admissao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'verbose_name_plural': 'Solicitações'},
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('CRI', 'Criada'), ('VGE', 'Validada pelo Gestor'), ('RGE', 'Recusada pelo Gestor'), ('DEF', 'Deferido'), ('RRH', 'Recusada pelo RH'), ('CON', 'Concluida')], default='CON', max_length=3),
            preserve_default=False,
        ),
    ]
