# Generated by Django 4.1.7 on 2023-04-07 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ponto', '0003_alter_customuser_data_admissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_admissao',
            field=models.DateField(default=datetime.datetime(2023, 4, 7, 18, 34, 54, 853598, tzinfo=datetime.timezone.utc), verbose_name='Data de admissão'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_senha',
            field=models.DateField(default=datetime.datetime(2023, 4, 7, 18, 34, 54, 853598, tzinfo=datetime.timezone.utc), verbose_name='Data da ultima troca de senha'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_criacao',
            field=models.DateField(default=datetime.datetime(2023, 4, 7, 18, 34, 54, 857599, tzinfo=datetime.timezone.utc), verbose_name='Data de criação'),
        ),
    ]
