# Generated by Django 4.1.7 on 2023-03-08 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ponto', '0003_alter_solicitacao_options_solicitacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gestor',
            field=models.ManyToManyField(to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_admissao',
            field=models.DateField(default=datetime.date(2023, 3, 8), verbose_name='Data de admissão'),
        ),
    ]
