# Generated by Django 4.1.7 on 2023-03-14 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0005_alter_customuser_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_senha',
            field=models.DateField(default=datetime.date(2023, 3, 14), verbose_name='Data da ultima troca de senha'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_admissao',
            field=models.DateField(default=datetime.date(2023, 3, 14), verbose_name='Data de admissão'),
        ),
    ]
