# Generated by Django 4.1.7 on 2023-03-21 19:26

from django.db import migrations
import ponto.models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0008_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', ponto.models.UserManager()),
            ],
        ),
    ]
