# Generated by Django 4.1.7 on 2023-03-21 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0009_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_admissao',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 22, 40, 7, 528361, tzinfo=datetime.timezone.utc), verbose_name='Data de admissão'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_senha',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 22, 40, 7, 528361, tzinfo=datetime.timezone.utc), verbose_name='Data da ultima troca de senha'),
        ),
    ]
