# Generated by Django 4.1.7 on 2023-03-29 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0010_alter_customuser_data_admissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='data_criacao',
            field=models.DateField(default=datetime.datetime(2023, 3, 29, 14, 17, 24, 35377, tzinfo=datetime.timezone.utc), verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_admissao',
            field=models.DateField(default=datetime.datetime(2023, 3, 29, 14, 17, 24, 27364, tzinfo=datetime.timezone.utc), verbose_name='Data de admissão'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_senha',
            field=models.DateField(default=datetime.datetime(2023, 3, 29, 14, 17, 24, 27364, tzinfo=datetime.timezone.utc), verbose_name='Data da ultima troca de senha'),
        ),
    ]
